name: test

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.21"
          cache-dependency-path: |
            go.sum
      - name: Checkout latest commit
        uses: actions/checkout@v3
      - name: Run tests
        run: |
          go test -v ./...
          go vet -v ./...
      - name: Compile examples
        working-directory: examples
        run: go build -o=/dev/null -v ./...
